apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{ .Values.persistentVolume.name }}"
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  accessModes:
    - {{ .Values.persistentVolume.accessModes }}
  resources:
    requests:
      storage: "{{ .Values.persistentVolume.size }}Gi"
