apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployments.deployment1.service.name }}
spec:
  type: {{ .Values.deployments.deployment1.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.deployments.deployment1.service.port }}
      protocol: TCP
  selector: 
    app: {{ .Release.Name }}-deployment1
