apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: "{{ .Release.Name }}-ingress1"
spec:
  ingressClassName: haproxy
  rules:
    - host: "{{ .Values.deployments.deployment1.service.name }}.{{ .Release.Namespace }}.{{ .Values.deployments.deployment1.ingress.domain }}"
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.deployments.deployment1.service.name }}
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
